import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'dev.architectury.loom' version '1.10-SNAPSHOT'
    id 'net.darkhax.curseforgegradle' version '1.1.+'
}

group = project.maven_group
version = project.minecraft_version + "-" + project.mod_version

base {
    archivesName = project.archives_name
}

loom {
    silentMojangMappingsLicense()

    forge {
        mixinConfig 'doespotatotick.mixins.json'
    }
}

repositories {
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    minecraft "net.minecraft:minecraft:$project.minecraft_version"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${project.parchment_version}@zip")
    }
    forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
    modImplementation("curse.maven:ftb-chunks-forge-314906:6431735")
    modImplementation("curse.maven:ftb-library-forge-404465:6164053")
    modImplementation("curse.maven:open-parties-and-claims-636608:6242869")
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }
}

java {
    withSourcesJar()
    if (version.startsWith("1.16.5")) {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    } else {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

tasks.withType(JavaCompile).configureEach {
    if (version.startsWith("1.16.5")) {
        it.options.release = 8
    } else {
        it.options.release = 17
    }
}

String currentChangeLog = file("CHANGELOG.md").getText("UTF-8")

String[] javaVersions = ["Java 17", "Java 21", "Java 22"]

if (minecraft_version == "1.16.5") {
    javaVersions = ["Java 17", "Java 21", "Java 22", "Java 8"]
}

tasks.register("publishCurseForge", TaskPublishCurseForge) {
    apiToken = System.getenv("CURSEFORGE_TOKEN")
    disableVersionDetection()

    def mainFile = upload(cf_project_id, remapJar)
    mainFile.displayName = "${archives_name}-${version}"
    mainFile.releaseType = "release"
    mainFile.changelog = currentChangeLog
    mainFile.changelogType = "markdown"
    mainFile.addModLoader("Forge")
    mainFile.addJavaVersion(javaVersions)
    mainFile.addGameVersion(minecraft_version)

    def sourcesFile = mainFile.withAdditionalFile(sourcesJar)

    sourcesFile.changelog = currentChangeLog
    sourcesFile.changelogType = "markdown"
}