org.gradle.jvmargs = -Xmx8192m -XX:MaxMetaspaceSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel = true
org.gradle.caching = true

loom.platform = forge

mod_version = 5.5.1
maven_group = me.kall.doespotatotick
archives_name = doespotatotick

minecraft_version = 1.18.2
mixinextras_version = 0.5.0

cf_project_id=825355

use_shadow=false
use_mixin=true
use_mixin_extras=false
use_duplicationless=true

claim_integration=true
embeddium_integration=true