modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "doespotatotick"
version = "${version}"
displayName = "DoesPotatoTick"
authors = "TeamPotato"
description = '''
A Minecraft Mod.
'''