modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "doespotatotick"
version = "${version}"
displayName = "DoesPotatoTick"
authors = "Kall"
description = '''
A Minecraft mod
'''
#logoFile = ""

[[dependencies.doespotatotick]]
modId="duplicationless"
mandatory=true
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "doespotatotick.mixins.json"
